name: Deploy to Azure Functions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: airesumeadvisor-fastapi
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'
  PYTHON_VERSION: '3.11'

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Cache pip packages
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov pytest-asyncio

    - name: Run Pre-deployment Tests (Level 3)
      env:
        # 主要 LLM 服務
        AZURE_OPENAI_API_KEY: ${{ secrets.AZURE_OPENAI_API_KEY }}
        AZURE_OPENAI_ENDPOINT: ${{ secrets.AZURE_OPENAI_ENDPOINT }}
        LLM2_API_KEY: ${{ secrets.LLM2_API_KEY || secrets.AZURE_OPENAI_API_KEY }}
        LLM2_ENDPOINT: ${{ secrets.LLM2_ENDPOINT || secrets.AZURE_OPENAI_ENDPOINT }}
        # GPT-4.1 mini
        GPT41_MINI_JAPANEAST_API_KEY: ${{ secrets.GPT41_MINI_JAPANEAST_API_KEY }}
        GPT41_MINI_JAPANEAST_ENDPOINT: ${{ secrets.GPT41_MINI_JAPANEAST_ENDPOINT }}
        GPT41_MINI_JAPANEAST_DEPLOYMENT: "gpt-4-1-mini-japaneast"
        GPT41_MINI_JAPANEAST_API_VERSION: "2025-01-01-preview"
        # 嵌入服務
        EMBEDDING_API_KEY: ${{ secrets.EMBEDDING_API_KEY || secrets.AZURE_OPENAI_API_KEY }}
        EMBEDDING_ENDPOINT: ${{ secrets.EMBEDDING_ENDPOINT }}
        # 其他必要設定
        JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY || 'test-secret-key' }}
        JWT_ALGORITHM: HS256
        JWT_EXPIRE_MINUTES: 30
        # LLM 模型配置
        LLM_MODEL_KEYWORDS: "gpt41-mini"
        LLM_MODEL_DEFAULT: "gpt4o-2"
        # 功能旗標
        ENABLE_LLM_MODEL_OVERRIDE: "true"
        ENABLE_LLM_MODEL_HEADER: "true"
      run: |
        echo "Running Level 3 integration tests..."
        echo "注意: 根據 CLAUDE.md，Claude Code 已執行適當層級測試 (Level 0-3)"
        
        # Make precommit.sh executable
        chmod +x ./precommit.sh
        
        # Run Level 3 tests
        ./precommit.sh --level-3 --parallel --no-coverage

  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Azure
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Zip artifact for deployment
      run: |
        # Exclude unnecessary files
        zip -r deploy.zip . \
          -x "*.git*" \
          -x "venv/*" \
          -x "__pycache__/*" \
          -x "tests/*" \
          -x ".pytest_cache/*" \
          -x "*.md" \
          -x ".github/*" \
          -x "local.settings.json" \
          -x ".serena/*" \
          -x ".claude/*" \
          -x "*.code-workspace"

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure Functions
      run: |
        az functionapp deployment source config-zip \
          --resource-group airesumeadvisorfastapi \
          --name ${{ env.AZURE_FUNCTIONAPP_NAME }} \
          --src deploy.zip

    - name: Check deployment health
      run: |
        sleep 30
        echo "🔍 Checking deployment health..."
        
        # First try without authentication
        echo "Testing root endpoint without auth..."
        ROOT_CHECK=$(curl -s -o /dev/null -w "%{http_code}" "https://${{ env.AZURE_FUNCTIONAPP_NAME }}.azurewebsites.net/")
        echo "Root endpoint returned: $ROOT_CHECK"
        
        # Then try with function key
        if [ -n "${{ secrets.FUNCTION_KEY }}" ]; then
          echo "Testing health endpoint with function key..."
          HEALTH_CHECK=$(curl -s -o /dev/null -w "%{http_code}" "https://${{ env.AZURE_FUNCTIONAPP_NAME }}.azurewebsites.net/api/v1/health?code=${{ secrets.FUNCTION_KEY }}")
          echo "Health endpoint returned: $HEALTH_CHECK"
          
          if [ $HEALTH_CHECK -eq 200 ]; then
            echo "✅ Deployment successful - Health check passed"
          elif [ $HEALTH_CHECK -eq 401 ]; then
            echo "⚠️  Health check returned 401 - Function key might be incorrect"
            echo "Please update FUNCTION_KEY in GitHub Secrets"
            # Don't fail the deployment, just warn
          else
            echo "❌ Deployment failed - Health check returned $HEALTH_CHECK"
            exit 1
          fi
        else
          echo "⚠️  FUNCTION_KEY not found in secrets - skipping authenticated health check"
          if [ $ROOT_CHECK -eq 200 ] || [ $ROOT_CHECK -eq 401 ]; then
            echo "✅ Deployment appears successful (root endpoint is responding)"
          else
            echo "❌ Deployment might have failed - root endpoint returned $ROOT_CHECK"
            exit 1
          fi
        fi

  notify:
    runs-on: ubuntu-latest
    name: Notify deployment status
    needs: deploy
    if: always()
    
    steps:
    - name: Send notification
      run: |
        if [ "${{ needs.deploy.result }}" == "success" ]; then
          echo "🎉 Deployment to Azure Functions successful!"
        else
          echo "❌ Deployment to Azure Functions failed!"
        fi