name: Deploy to Azure Functions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: airesumeadvisor-fastapi
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'
  PYTHON_VERSION: '3.11'

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Cache pip packages
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov pytest-asyncio

    - name: Run unit tests
      run: |
        pytest tests/unit/ -v --cov=src --cov-report=xml --cov-report=term

    - name: Check code quality
      run: |
        pip install black isort mypy
        black --check src/ tests/
        isort --check-only src/ tests/
        mypy src/ --ignore-missing-imports

  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Azure
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Zip artifact for deployment
      run: |
        # Exclude unnecessary files
        zip -r deploy.zip . \
          -x "*.git*" \
          -x "venv/*" \
          -x "__pycache__/*" \
          -x "tests/*" \
          -x ".pytest_cache/*" \
          -x "*.md" \
          -x ".github/*" \
          -x "local.settings.json" \
          -x ".serena/*" \
          -x ".claude/*" \
          -x "*.code-workspace"

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure Functions
      run: |
        az functionapp deployment source config-zip \
          --resource-group airesumeadvisorfastapi \
          --name ${{ env.AZURE_FUNCTIONAPP_NAME }} \
          --src deploy.zip

    - name: Check deployment health
      run: |
        sleep 30
        HEALTH_CHECK=$(curl -s -o /dev/null -w "%{http_code}" "https://${{ env.AZURE_FUNCTIONAPP_NAME }}.azurewebsites.net/health?code=${{ secrets.FUNCTION_KEY }}")
        if [ $HEALTH_CHECK -eq 200 ]; then
          echo "✅ Deployment successful - Health check passed"
        else
          echo "❌ Deployment failed - Health check returned $HEALTH_CHECK"
          exit 1
        fi

  notify:
    runs-on: ubuntu-latest
    name: Notify deployment status
    needs: deploy
    if: always()
    
    steps:
    - name: Send notification
      run: |
        if [ "${{ needs.deploy.result }}" == "success" ]; then
          echo "🎉 Deployment to Azure Functions successful!"
        else
          echo "❌ Deployment to Azure Functions failed!"
        fi