name: Test Function Key

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Test Function Key
      run: |
        echo "🔑 Testing Function Key..."
        
        # Test health endpoint with function key
        RESPONSE=$(curl -s -w "\n%{http_code}" "https://airesumeadvisor-fastapi.azurewebsites.net/health?code=${{ secrets.FUNCTION_KEY }}")
        HTTP_CODE=$(echo "$RESPONSE" | tail -n1)
        BODY=$(echo "$RESPONSE" | head -n-1)
        
        echo "HTTP Status: $HTTP_CODE"
        echo "Response Body: $BODY"
        
        if [ "$HTTP_CODE" = "200" ]; then
          echo "✅ Function Key is valid!"
        else
          echo "❌ Function Key test failed with status $HTTP_CODE"
          exit 1
        fi